### ISSUE TITLE
添加了版本号打包之后访问回报错

### ISSUE THREAD

**Issue by baihuijun** [liuhean2021/vite-plugin-add-version#1]
![Snipaste_2023-04-11_11-13-44](https://user-images.githubusercontent.com/52630363/231046902-2d0daa6f-2e0d-4243-ad9c-d1a33eb9dee8.png)

**Comment by liuhean2021** [comment]
看起来是包之外的错误，package.json文件里是否添加了version字段
<img width="282" alt="截屏2023-04-11 16 51 42" src="https://user-images.githubusercontent.com/10606051/231107889-c875d60d-c798-40a4-a653-f7c0e5d4b32c.png">

**Comment by baihuijun** [comment]
有的，vite是4.2版本的不知道是否跟这个有关系

**Comment by baihuijun** [comment]
有的，我重新在demo里面试了没问题  可能跟我配置有关吧

**Comment by liuhean2021** [comment]
关闭问题。
